apiVersion: v1
kind: ConfigMap
metadata:
  name: test2
  namespace: foo
data:
  mortacci: "1.1.0"
  foo: "If this confimap appears automagically then argo does the reapplication"
  helm-name-version: {{ include "test.chart" . }} 
  helm-version: {{ .Chart.Version | quote }}
  helm-appversion: {{ .Chart.AppVersion | quote }}

