# Note this workflow is only maintained in this repo
# It should be invoked from each chart's repo

name: vp-patterns/update-umbrella-repo
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  update-umbrella-repo:
    if: ${{ github.repository != 'mbaldessari/charts-test' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Verify Chart version matches tag version
        run: |-
          export TAG=${{ github.ref_name }}
          git_tag="${TAG#v}"
          chart_tag=$(yq -r '.version' Chart.yaml)
          if [ "${git_tag}" != "${chart_tag}" ]; then
            echo "chart version (${chart_tag}) did not match git version (${git_tag})"
            exit 1
          fi
      - name: Invoke umbrella-repo publish charts workflow
        id: update
        env:
          GH_TOKEN: ${{ secrets.CHARTS_TEST_REPO }}
        run: |-
          gh workflow run publish-charts.yml \
            --repo mbaldessari/charts-test \
            --ref main \
            -f SOURCE_TAG="${{ github.ref_name }}" \
            -f SOURCE_REPO="${{ github.repository }}"
